database: mysql

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      encoding: UTF-8
      data-locations: "classpath:db/${database}/data.sql"
      schema-locations: "classpath:db/${database}/schema.sql"

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(-){faint} %clr([%t]){faint} %clr(%-40logger{39}){cyan}[%line]%clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: INFO
    com.github.fenixsoft: DEBUG
