drop database star;
create database star;

DROP TABLE IF EXISTS SYAIN_MAIN;
DROP TABLE IF EXISTS SYAIN_RIREKI;
DROP TABLE IF EXISTS SYAIN_KEIREKI;
DROP TABLE IF EXISTS SYAIN_KYUYO;
DROP TABLE IF EXISTS SYAIN_KEIHI;
DROP TABLE IF EXISTS SYAIN_KOUTSUHI;
DROP TABLE IF EXISTS TORIHIKISAKI_MAIN;
DROP TABLE IF EXISTS TORIHIKISAKI_TANTOU;
DROP TABLE IF EXISTS TG_SETTING;
DROP TABLE IF EXISTS USER_AUTH;
DROP TABLE IF EXISTS USER_ACCESS_LOG;

CREATE TABLE SYAIN_MAIN
(
    SYAIN_ID                 INT(11) PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME_KANJI         VARCHAR(15) NOT NULL,
    LAST_NAME_KANJI          VARCHAR(15) NOT NULL,
    FIRST_NAME_KANA          VARCHAR(15) NOT NULL,
    LAST_NAME_KANA           VARCHAR(15) NOT NULL,
    FIRST_NAME_EIGO          VARCHAR(15) NOT NULL,
    LAST_NAME_EIGO           VARCHAR(15) NOT NULL,
    SEIBETU                  INT(11) COMMENT '0:女 1:男',
    TANJYOBI                 DATE,
    KOKUSEKI                 INT(11),
    SYUSSINN                 VARCHAR(30),
    HAIGUSYA                 INT(11)     NOT NULL COMMENT '０：なし　１：あり',
    PASSPORT_NUM             VARCHAR(20),
    PASSPORT_END_DATE        DATE,
    VISA_KIKAN               INT(11),
    VISA_END_DATE            DATE,
    ZAIRYU_SIKAKU            INT(11),
    KOJIN_NUM                VARCHAR(20),
    ZAIRYU_NUM               VARCHAR(20),
    SYOZOKU_KAISYA           INT(11)     NOT NULL,
    NYUUSYA_DATE             DATE,
    TAISYA_DATE              DATE,
    SYOKUGYO_KIND            INT(11)     NOT NULL,
    RAINITI_DATE             DATE,
    BIKOU                    VARCHAR(255),
    YUUBIN                   CHAR(8),
    JYUSYO_1                 VARCHAR(100),
    JYUSYO_2                 VARCHAR(100),
    MOYORI_EKI               VARCHAR(30),
    TEL                      VARCHAR(15),
    EMAIL                    VARCHAR(50),
    WECHAT                   VARCHAR(30),
    LINE                     VARCHAR(30),
    BOKOKU_JYUSYO            VARCHAR(255),
    BOKOKU_KINNKYUU_RENNRAKU VARCHAR(255),
    SAISYUU_GAKUREKI         INT(11)     NOT NULL,
    GAKKOU_NAME              VARCHAR(100),
    SENNMOM_NAME             VARCHAR(100),
    SOTUGYO_DATE             DATE,
    GYUMU_NENSU              FLOAT,
    IT_OS                    VARCHAR(100),
    IT_GENGO                 VARCHAR(100),
    IT_DB                    VARCHAR(100),
    IT_WEB_SERVER            VARCHAR(100),
    IT_FW                    VARCHAR(100),
    IT_OTHER                 VARCHAR(100),
    IT_BIKOU                 VARCHAR(1024),
    DELETE_FLAG              INT(11)     NOT NULL,
    TOUROKUBI                DATETIME,
    KOUSINNBI                DATETIME
)
    DEFAULT CHARACTER SET UTF8
    COLLATE UTF8_UNICODE_CI;

CREATE TABLE SYAIN_RIREKI
(
    SYAIN_ID      INT(11) NOT NULL,
    KAISIBI       DATE    NOT NULL,
    SYURYOBI      DATE,
    KAISYA_NAME   VARCHAR(100),
    BUSYO         VARCHAR(100),
    TOUROKUBI     DATETIME,
    KOUSINNBI     DATETIME,
    PJ_NAME       VARCHAR(100),
    TAINITI_FLAG  INT(11),
    BASYO         INT(11),
    KIBO          INT(11),
    GYOSYU        INT(11),
    KAIHATUKANKYO INT(11),
    UNYOUKANKYO   INT(11),
    GENGO         VARCHAR(100),
    DB            VARCHAR(100),
    TOOL          VARCHAR(100),
    TANTOU        INT(11),
    SAGYOHANI     INT(11),
    GAIYOU        VARCHAR(1024),
    PRIMARY KEY (SYAIN_ID, KAISIBI)
)
    DEFAULT CHARACTER SET UTF8
    COLLATE UTF8_UNICODE_CI;

CREATE TABLE SYAIN_KEIREKI
(
    SYAIN_ID      INT(11) NOT NULL,
    KAISIBI       DATE    NOT NULL,
    SYURYOBI      DATE,
    PJ_NAME       VARCHAR(100),
    TAINITI_FLAG  INT(11),
    BASYO         INT(11),
    KIBO          INT(11),
    GYOSYU        INT(11),
    KAIHATUKANKYO INT(11),
    UNYOUKANKYO   INT(11),
    GENGO         VARCHAR(100),
    DB            VARCHAR(100),
    TOOL          VARCHAR(100),
    TANTOU        INT(11),
    SAGYOHANI     INT(11),
    GAIYOU        VARCHAR(1024),
    TOUROKUBI     DATETIME,
    KOUSINNBI     DATETIME,
    PRIMARY KEY (SYAIN_ID, KAISIBI)
)
    DEFAULT CHARACTER SET UTF8
    COLLATE UTF8_UNICODE_CI
;

CREATE TABLE SYAIN_KYUYO
(
    SYAIN_ID           INT(11)    NOT NULL,
    KAISHI_NENGETSU    VARCHAR(6) NOT NULL,
    SYURYO_NENGETSU    VARCHAR(6) COMMENT '終了年月: 最後の記録以外、NULL不可',
    KIHONKYU           INT(11),
    SYOKUNOUKYU        INT(11),
    KOYOU_HOKEN_NO     VARCHAR(30),
    NANKIN_NO          VARCHAR(30),
    NANKIN_KIJYUN_GAKU INT(11),
    KENKOU_HOKEN_NO    VARCHAR(30),
    BIKOU              TEXT,
    TOUROKUBI          DATETIME,
    KOUSINNBI          DATETIME,
    PRIMARY KEY (SYAIN_ID, KAISHI_NENGETSU)
)
    DEFAULT CHARACTER SET UTF8
    COLLATE UTF8_UNICODE_CI;

CREATE TABLE SYAIN_KEIHI
(
    SYAIN_ID               INT,
    TEKIYOU_NENGETSU       VARCHAR(6),
    RENBAN                 INT,
    HIMOKU                 INT,
    KINGAKU                INT,
    KYAKUSAKI_SEIKYU_KUBUN INT,
    BIKOU                  VARCHAR(255),
    TOUROKUBI              DATETIME,
    KOUSINNBI              DATETIME,
    PRIMARY KEY (SYAIN_ID, TEKIYOU_NENGETSU, RENBAN)
)
    DEFAULT CHARACTER SET UTF8
    COLLATE UTF8_UNICODE_CI;


CREATE TABLE SYAIN_KOUTSUHI
(
    SYAIN_ID               INT,
    TEKIYOU_NENGETSU       VARCHAR(6),
    RENBAN                 INT,
    HIMOKU                 INT,
    SYUPPATSU_EKI          VARCHAR(30),
    TOUCHAKU_EKI           VARCHAR(30),
    KINGAKU                INT,
    KYAKUSAKI_SEIKYU_KUBUN INT,
    BIKOU                  VARCHAR(255),
    TOUROKUBI              DATETIME,
    KOUSINNBI              DATETIME,
    PRIMARY KEY (SYAIN_ID, TEKIYOU_NENGETSU, RENBAN)
)
    DEFAULT CHARACTER SET UTF8
    COLLATE UTF8_UNICODE_CI;

CREATE TABLE TORIHIKISAKI_MAIN
(
    TORIHIKI_ID         INT(11)      NOT NULL COMMENT '自動連番'
        PRIMARY KEY,
    TORIHIKI_NAME_ALL   VARCHAR(50)  NOT NULL,
    TORIHIKI_NAME_RYAKU VARCHAR(30)  NOT NULL,
    YUUBIN              CHAR(8)      NOT NULL,
    JYUSYO_1            VARCHAR(100) NOT NULL,
    JYUSYO_2            VARCHAR(100),
    TEL                 VARCHAR(15),
    FAX                 VARCHAR(15),
    URL                 VARCHAR(100),
    BIKOU               VARCHAR(255),
    DELETE_FLAG         INT(11)      NOT NULL COMMENT '論理削除　0:有効　1:削除',
    SEIKYUSYO_KUBUN_1   INT(11) COMMENT '請求書の郵送有無　0：無し　1：有り',
    SEIKYUSYO_KUBUN_2   INT(11) COMMENT '特定ファイル名　0：無し　1：有り',
    SEIKYUSYO_KUBUN_3   INT(11) COMMENT '案件名請求　0：無し　1：有り',
    SEIKYUSYO_KUBUN_4   INT(11) COMMENT '納品書付き　0：無し　1：有り',
    SEIKYUSYO_KUBUN_5   INT(11) COMMENT '請求書の提供　0：無し　1：本体　2：フォーマット',
    SEIKYUSYO_KUBUN_6   INT(11) COMMENT '請求単位　0：会社別　1：作業員別／案件名別　2：現場別　3：職部別',
    SEIKYUSYO_KUBUN_7   VARCHAR(255),
    SEIKYUSYO_KUBUN_8   VARCHAR(255),
    SEIKYUSYO_KUBUN_9   VARCHAR(255),
    SEIKYUSYO_KUBUN_10  VARCHAR(255),
    SEIKYUSYO_KUBUN_11  VARCHAR(255),
    HONSYA              INT(11),
    HONSYA_KOUZA        INT(11),
    KINYUKIKAN_CODE     VARCHAR(10),
    KINYUKIKAN_NAME     VARCHAR(50),
    SITEN_CODE          VARCHAR(10),
    SITEN_NAME          VARCHAR(50),
    KOUZA_KIND          INT COMMENT '1:普通　2:当座',
    KOUZA_NUM           VARCHAR(10),
    MEIGI_NAME          VARCHAR(50),
    TOUROKUBI           DATETIME,
    KOUSINNBI           DATETIME
);

CREATE TABLE IF NOT EXISTS TORIHIKISAKI_TANTOU
(
    TANTOU_ID   INT(11)     NOT NULL
        PRIMARY KEY,
    TORIHIKI_ID INT(11),
    FIRST_NAME  VARCHAR(20) NOT NULL,
    LAST_NAME   VARCHAR(20) NOT NULL,
    SYOZOKU     VARCHAR(50) COMMENT '所属: 管理本部など',
    YAKUSYOKU   VARCHAR(50) COMMENT '役職: 部長など',
    MAIL        VARCHAR(100),
    TEL         VARCHAR(15),
    JIMU_MAIL   INT(11) COMMENT '事務関連（請求・外注など）MAIL: 1:TO 2:CC',
    BIKOU       VARCHAR(255)
)
    DEFAULT CHARACTER SET UTF8
    COLLATE UTF8_UNICODE_CI;

CREATE TABLE USER_ACCESS_LOG
(
    ID         INT(11) NOT NULL
        PRIMARY KEY,
    USER_ID    INT(11),
    GAMEN_ID   VARCHAR(255),
    START_TIME DATETIME
)
    DEFAULT CHARACTER SET UTF8
    COLLATE UTF8_UNICODE_CI;


CREATE TABLE USER_AUTH
(
    USER_ID   INT         NOT NULL,
    USER_CODE VARCHAR(20) NOT NULL,
    USER_NAME VARCHAR(30) NOT NULL,
    PASSWORD  VARCHAR(50) NOT NULL COMMENT '暗号化すべき、MD5関数で実施可能。',
    USER_ROLE CHAR(1)     NOT NULL COMMENT 'S:システム管理者 A:統合管理者　B　営業担当　C経理担当　D：人事担当',
    IS_YOUKOU INT(11)     NOT NULL,
    PRIMARY KEY (USER_ID, USER_CODE)
)
    DEFAULT CHARACTER SET UTF8
    COLLATE UTF8_UNICODE_CI;


CREATE TABLE TG_SETTING
(
    CATEGORY1 INT(11)      NOT NULL,
    CATEGORY2 INT(11)      NOT NULL,
    CATEGORY3 INT(11)      NOT NULL,
    VALUE1    VARCHAR(100) NOT NULL,
    VALUE2    VARCHAR(100),
    VALUE3    VARCHAR(100),
    VALUE4    VARCHAR(100),
    VALUE5    VARCHAR(100),
    PRIMARY KEY (CATEGORY1, CATEGORY2, CATEGORY3)
);
